ALTER TABLE contracts
  ADD COLUMN IF NOT EXISTS client_signed TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS freelancer_signed TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS client_signed_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS freelancer_signed_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS client_signature VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS freelancer_signature VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS terms TEXT NULL;
