-- Use stored procedure to safely add columns on MySQL < 8.0 (no IF NOT EXISTS support)
DROP PROCEDURE IF EXISTS add_otp_columns;
DELIMITER $$
CREATE PROCEDURE add_otp_columns()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'otp_code') THEN
        ALTER TABLE users ADD COLUMN otp_code VARCHAR(10) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'otp_expires') THEN
        ALTER TABLE users ADD COLUMN otp_expires DATETIME NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'reset_token') THEN
        ALTER TABLE users ADD COLUMN reset_token VARCHAR(100) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'reset_token_expires') THEN
        ALTER TABLE users ADD COLUMN reset_token_expires DATETIME NULL;
    END IF;
END$$
DELIMITER ;
CALL add_otp_columns();
DROP PROCEDURE IF EXISTS add_otp_columns;
