ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_code VARCHAR(10) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_expires DATETIME NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_expires DATETIME NULL;
