-- Seed common skills for the platform
INSERT IGNORE INTO skills (name, category) VALUES
-- Development
('JavaScript', 'Development'),
('Python', 'Development'),
('Java', 'Development'),
('PHP', 'Development'),
('C#', 'Development'),
('Ruby', 'Development'),
('Go', 'Development'),
('Swift', 'Development'),
('Kotlin', 'Development'),
('TypeScript', 'Development'),
('React', 'Development'),
('Angular', 'Development'),
('Vue.js', 'Development'),
('Node.js', 'Development'),
('Django', 'Development'),
('Laravel', 'Development'),
('Spring Boot', 'Development'),
('ASP.NET', 'Development'),
('Flutter', 'Development'),
('React Native', 'Development'),
('iOS Development', 'Development'),
('Android Development', 'Development'),
('Full Stack Development', 'Development'),
('Frontend Development', 'Development'),
('Backend Development', 'Development'),
('Mobile App Development', 'Development'),
('Web Development', 'Development'),
('API Development', 'Development'),
('Database Design', 'Development'),
('SQL', 'Development'),
('MongoDB', 'Development'),
('PostgreSQL', 'Development'),
('MySQL', 'Development'),
('Redis', 'Development'),
('GraphQL', 'Development'),
('REST API', 'Development'),
('Microservices', 'Development'),
('DevOps', 'Development'),
('Docker', 'Development'),
('Kubernetes', 'Development'),
('AWS', 'Development'),
('Azure', 'Development'),
('Google Cloud', 'Development'),
('CI/CD', 'Development'),
('Git', 'Development'),
('Agile', 'Development'),
('Scrum', 'Development'),

-- Design
('UI/UX Design', 'Design'),
('Graphic Design', 'Design'),
('Logo Design', 'Design'),
('Brand Identity', 'Design'),
('Web Design', 'Design'),
('Mobile Design', 'Design'),
('Illustration', 'Design'),
('Adobe Photoshop', 'Design'),
('Adobe Illustrator', 'Design'),
('Figma', 'Design'),
('Sketch', 'Design'),
('Adobe XD', 'Design'),
('InDesign', 'Design'),
('After Effects', 'Design'),
('Premiere Pro', 'Design'),
('Video Editing', 'Design'),
('Motion Graphics', 'Design'),
('3D Modeling', 'Design'),
('Blender', 'Design'),
('AutoCAD', 'Design'),
('Animation', 'Design'),
('Typography', 'Design'),
('Color Theory', 'Design'),
('Wireframing', 'Design'),
('Prototyping', 'Design'),

-- Writing & Translation
('Content Writing', 'Writing'),
('Copywriting', 'Writing'),
('Technical Writing', 'Writing'),
('Blog Writing', 'Writing'),
('SEO Writing', 'Writing'),
('Creative Writing', 'Writing'),
('Proofreading', 'Writing'),
('Editing', 'Writing'),
('Translation', 'Writing'),
('Amharic Translation', 'Writing'),
('English to Amharic', 'Writing'),
('Amharic to English', 'Writing'),
('Transcription', 'Writing'),
('Resume Writing', 'Writing'),
('Grant Writing', 'Writing'),

-- Marketing & Sales
('Digital Marketing', 'Marketing'),
('Social Media Marketing', 'Marketing'),
('SEO', 'Marketing'),
('SEM', 'Marketing'),
('Content Marketing', 'Marketing'),
('Email Marketing', 'Marketing'),
('Facebook Ads', 'Marketing'),
('Google Ads', 'Marketing'),
('Instagram Marketing', 'Marketing'),
('LinkedIn Marketing', 'Marketing'),
('Influencer Marketing', 'Marketing'),
('Brand Strategy', 'Marketing'),
('Market Research', 'Marketing'),
('Sales', 'Marketing'),
('Lead Generation', 'Marketing'),
('CRM', 'Marketing'),
('Analytics', 'Marketing'),
('Google Analytics', 'Marketing'),

-- Business & Admin
('Data Entry', 'Business'),
('Virtual Assistant', 'Business'),
('Customer Service', 'Business'),
('Project Management', 'Business'),
('Business Analysis', 'Business'),
('Financial Analysis', 'Business'),
('Accounting', 'Business'),
('Bookkeeping', 'Business'),
('Excel', 'Business'),
('PowerPoint', 'Business'),
('Word', 'Business'),
('QuickBooks', 'Business'),
('Salesforce', 'Business'),
('Human Resources', 'Business'),
('Recruitment', 'Business'),
('Legal Writing', 'Business'),
('Contract Review', 'Business'),

-- Other
('Photography', 'Creative'),
('Photo Editing', 'Creative'),
('Voice Over', 'Creative'),
('Audio Editing', 'Creative'),
('Music Production', 'Creative'),
('Podcast Editing', 'Creative'),
('Game Development', 'Development'),
('Unity', 'Development'),
('Unreal Engine', 'Development'),
('Blockchain', 'Development'),
('Smart Contracts', 'Development'),
('Machine Learning', 'Development'),
('AI Development', 'Development'),
('Data Science', 'Development'),
('Data Analysis', 'Development'),
('Cybersecurity', 'Development'),
('Penetration Testing', 'Development'),
('Network Administration', 'Development'),
('System Administration', 'Development'),
('WordPress', 'Development'),
('Shopify', 'Development'),
('E-commerce', 'Business'),
('Consulting', 'Business');
